import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  callContainer: {
    flex: 1,
    position: 'absolute',
    bottom: 0,
    top: 0,
    left: 0,
    right: 0,
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    paddingTop: 40,
    marginBottom: 10,
  },
  input: {
    height: 48,
    borderRadius: 5,
    overflow: 'hidden',
    backgroundColor: 'white',
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 16,
    borderColor: 'gray',
    borderWidth: 1,
  },

  connectButton: {
    backgroundColor: '#44a4a5',
    marginLeft: 30,
    marginRight: 30,
    marginTop: 20,
    height: 48,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  connectButtonTitle: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  disabledButton: {
    color: 'white',
    backgroundColor: 'gray',
  },
  localVideo: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 100,
    height: 120,
    backgroundColor: 'blue',
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 10000,
    elevation: 10000,
  },
  remoteGrid: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    zIndex: 100,
    elevation: 0,
  },
  remoteVideo: {
    width: '100%',
    height: '100%',
    zIndex: 0,
    elevation: 0,
  },
  videoTip: {
    zIndex: 100,
    elevation: 100,
    position: 'absolute',
    left: '50%',
    bottom: 120,
    transform: [{translateX: -50}],
    justifyContent: 'center',
    gap: 8,
    // height: 100,
    // backgroundColor: 'rgba(255, 255, 255, 0.1)',
    blurRadius: 90,
  },
  videoTipText: {
    color: 'white',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  optionsContainer: {
    zIndex: 100,
    elevation: 100,
    position: 'absolute',
    left: 0,
    bottom: 0,
    right: 0,
    height: 100,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    flexDirection: 'row',
    alignItems: 'center',
    blurRadius: 90,
  },
  optionButton: {
    width: 60,
    height: 60,
    marginLeft: 8,
    marginRight: 8,
    borderRadius: 8,
    backgroundColor: '#F8F9FA',
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  icon: {
    width: 22,
    height: 22,
    resizeMode: 'contain',
  },
  buttonOff: {
    backgroundColor: '#F04A43',
  },
});
